title: Remember your past
author: Илья Малышев
email: your-email@domain.com
theme: minima
description: Это сборник старых мемов. Пора вернуть ваш 2007

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
